### PR TITLE
Split Recording functionality

### PR DESCRIPTION
**Pull request by READSEARCH**
Added a Split Recording functionality for multiple recordings, with an automatic numbering of the files and an automatic 'save to' option.

### CODE REVIEW

**Comment by PaulBoersma** [comment]
Praat doesn't do any automatic saving anywhere (except to the preferences files). The Praat way to save multiple sounds would be to have them in the Objects list (e.g. by pressing Apply after each recording), and then save them with a command from the save menu.

**Comment by Artengar** [comment]
Indeed, Praat *did* not do this;
That is the reason we wrote this new code so it could offer that functionality. It saved us a lot of time while doing our research. And because it could be helpful for others to, we hoped you could implement our work into Praat. All work is done and the code for this functionality is attached to our first comment.
Here is a link how it looked on Mac: http://postimg.org/image/l9fwn3x8r/

**Comment by READSEARCH** [comment]
Indeed, Praat *did* not do this;
That is the reason we wrote this new code so it could offer that functionality. It saved us a lot of time while doing our research. And because it could be helpful for others to, we hoped you could implement our work into Praat. All work is done and the code for this functionality is attached to our first comment.
Here is a link how it looked on Mac: http://postimg.org/image/l9fwn3x8r/

**Comment by PaulBoersma** [comment]
Well, a program doesn't only have functionality; it also has design (i.e. predictability). Praat has 8000 commands, and none of them do autosaving, and that's by design. All the saving is done via the Save menu in the Objects window or via one of the many File menus in the other windows, and that's predictable. If you introduce autosaving in a small corner of Praat and not everywhere else, Praat will become messy, and the SoundRecorder extension that you created indeed looks a bit messy, because it adds just as many buttons to the window as a typical file-selector window has. Fortunately, it is possible to introduce your functionality in a way that is compatible with Praat's design: (1) click Save to List in the SoundRecorder after each sound, and then (2) select all the Sound objects that you recorded and choose "Save as multiple WAV files..." from the Save menu (e.g. the Sound objects "hello", "cheers" and "goodbye" will be saved as hello.wav, cheers.wav and goodbye.wav in the directory that you choose). This would not be more typing or more mouse clicks than your solution, and it would work for *all* sounds that have been created in *any* way, and it would work very much like the commands "Save as multiple binary files" and "Save as multiple text files", which would work for all 300 object types, not just for Sound. Now, some of the buttons that I proposed here haven't been implemented yet, but I think they do adhere to Praat's design philosophy, so if you implement *those* (with all the necessary stuff, such as warnings against overwriting), then I would honor your pull request.

**Comment by Artengar** [comment]
You made your point clear, and I understand your philosophy.

Thanks for the constructive criticism! I will have a look with the programmer and look into what is possible (if, and when).

**Pull request closed without merging**
